### PR TITLE
:construction_worker: Add `macOS` platform to binary release workflow

### LINKED ISSUE #310: [TRACKING] Build native binaries during release
An issue to capture the ask for building native binaries during release. The following platforms are planned to be supported:

- [x] Linux (x86_64)
- [x] macOS (x86_64, arm64)
- [x] Windows (x86_64)

## Additional context

There are a few actions which have already been defined that just need testing and refining. The following are relevant:

- [`build-server`](https://github.com/stumpapp/stump/blob/main/.github/actions/build-server/action.yml)
- [`build-web`](https://github.com/stumpapp/stump/blob/main/.github/actions/build-web/action.yml)

Realistically, caching needs to be implemented to speed up the build process before I would want to include this in the release process.

### PR DESCRIPTION
**Pull request by aaronleopold**
This builds off of the work from #369 to close #310

I'll try to test it during the week with some debug commits to trigger the workflow before merging this in

### CODE REVIEW

**Review by JMicheli — COMMENTED** [review]
Looks good to me!

One thing I'm not familiar with in the MacOS context - do you need two binaries, one for Apple Silicon and one for non-Apple hardware?

**Comment by aaronleopold** [comment]
> One thing I'm not familiar with in the MacOS context - do you need two binaries, one for Apple Silicon and one for non-Apple hardware?

Ah yeah, I think you're correct. I'll look more into it this week to see how much would change. It might just be a matter of adding an additional matrix for arm macOS vs intel

**Comment by aaronleopold** [comment]
Just because I find it interesting, the builds completed in the following order:

- macOS (ARM) 11m 32s
- Ubuntu 13m 20s
- macOS (intel) 15m 17s
- Windows 24m 1s

**Comment by DieselTech** [comment]
Interesting but weird at the same time. Then again `rustup` on windows is a bit jank.

**Comment by aaronleopold** [comment]
Just verified the arm binary worked as expected, so I reverted the debug commit to trigger the workflow and I'll merge this momentarily. Thanks for the catch @JMicheli!

**Pull request merged**
